/**
* @module documentModel
*
* an example of a model generated by the @function ebserve.model() when given @param {Array} SCHEMA_JSON = ["_id: Number", "Name: String", "Email: String", "Age: Number"];
*
* @exports Document a mongoose.model of the mongoose.Schema as created by ebserve.model()
*/
MONGOOSE = require('mongoose'); 
const {Schema, model} = MONGOOSE; 

const documentSchema = new Schema({
	_id: Number,
	Name: String,
	Email: String,
	Age: Number,
})

const Document = model("Document", documentSchema)
module.exports = {"Document": Document}
